installer/targets/ros/install.bash

I would propose to use -by default- catkin build instead of catkin_make
tue-make still supports the (current) use of catkin_make
Rationale can be found here: https://catkin-tools.readthedocs.io/en/latest/history.html
Anyone to argue for or against this?

use catkin build instead of catkin_make

---

installer/targets/amigo-start/install.yaml

The ROSBridge websocket server that provides a websocket JSON API
requires the message definitions in order to construct the bridged
interfaces. Added the missing message definitions to amigo-start target
in order to make the web clients works fully.

fix(): Added missing message definitions for websocket server

---

installer/targets/ros-rtt_tue_msgs/install.yaml

rtt_control_components does depend on it. Rein will move the repo back from graveyard.

restore rtt_tue_msgs target, but now in YAML

---

installer/scripts/tue-install-impl

This way install.bash scripts can use pip manually too. (Which should not be done too much)

Install pip at begin of installer

---

installer/targets/robot-user/setup

This reverts commit 9f6cbea558fedf15bf6d0c6e4527f062a8022330.
```
ROS master URI is not set
The traceback for the exception was written to the log file
```

Revert "unset ROS_MASTER_URI"

---

installer/targets/pycharm/install.bash

Pycharm is now installed by snap, directly from jetbrains. All PPA's are maintained by individuals. The PPA version was installed in an other location, than the snap. Therefore the PPA version needs to be removed.

remove old pycharm version

---

installer/scripts/tue-install-impl

- for easy checking of last install run
- TUE_INSTALL_TEMP_DIR is the same as TUE_INSTALL_STATE_DIR and wasn't used

use date_stamp for log instead of random id

---

installer/scripts/bootstrap-ros-indigo
installer/scripts/bootstrap-ros-jade
installer/scripts/bootstrap-ros-kinetic

Because tue-env init will stop when environment dir(ros/XX/.env) is already there. So bootstrap wasn't always succeeding when run for 2nd time.
The other option of changing the tue-env init function is incorrect in my opinion. That one should fail, if folders/files are already there.
The issue is that ~/.tue/user/envs/XX file is not always created. When this happens again, it is because of problems with creating/writing the file instead of not reaching that code.

move old environment files

---

installer/scripts/tue-install-impl

tmp folder of all sessions were removed, which will brake an other session if it is running.

Allow multiple sessions to be run at the same time

---

ci/.travis.yml.example
ci/.travis.yml.multiple_pkgs.example

TRAVIS_BRANCH implies target branch instead of source branch causing CI
to fail if dependencies changed.
Solution found in this thread:
https://github.com/travis-ci/travis-ci/issues/6652

Fix ci in case of PR

---

installer/targets/ros-kdl_parser/install.yaml

N.B.: not yet tested on new installation

fix(target)KDL parser uses kinetic devel branch

---

ci/build-package.sh

Right now CI will not fail, if a catkin test fails. This PR fixes it.
See: https://travis-ci.org/tue-robotics/navigation/builds/425252418

check results of unit tests

---

ci/build-package.sh

Exclude packages, whose folder does not exist, from catkin_test_results. This should only be the case for metapackages.

Exlude meta-packages from catkin test

---

installer/targets/robot-user/setup

This alias wasn't being used anywhere. Also, it was over writing the config file in .ssh

removed quickssh alias

---

installer/scripts/tue-install-impl.bash
installer/scripts/tue-install.bash

Git supports applying a command to a different folder. So no need to memorize the directory you came from

Stop unnecessary folder switching and remove code duplication in git install function

---

installer/tue-install-impl.bash

Let it be decided by the user self. So the user can set TUE_CUDA to use cuda in targets or not.
@LarsJanssenTUe This will prevent the issue tensorflow issue to happen again by running `tue-get update`

Remove auto check for cuda in installer.

---

setup/tue-functions.bash

It was broken, because pkd_dir could also be a subfolder of a git repo. So `.git` would never be found.

fix tue-status

---

installer/tue-install-impl.bash

Lets say we have 100 targets are installed and 5 of them are not in targets repo anymore.
Currently there is no order in which their existence is checked. 
It may so happen that the first missing target is found after updating 20 targets and the installation will break. After fixing this missing target, the installer will again go through all the 20 targets and so on, which is a waste of time. 
This PR fixes this issue.
Fixes #403

Check and display all removed targets first

---

ci/.travis.yml.multiple_pkgs.example
ci/build-package.sh
ci/install-package.sh

Travis runs easily into a time limit when running on a multi-package repo. Therefore the result is actually useless as not all package can be tested.
Another flaw is that success is only determined on the success of the last package. See https://travis-ci.com/tue-robotics/navigation/builds/122691895, `amcl` fails on `map_server` (and many more errors), but because `voxel_grid` succeedes, the whole CI succeedes. This is completely incorrect. 
My proposed setup, runs all the packages in parallel by using the matrix functionality of travis. This prevents running into a timeout, because of running packages serial. (Single packages could still run in a timeout). Also the problem of a incorrect success status is fixed. Packages which haven't changed will not be installed and build. Those …

Change CI for multi-package repo

---

setup/tue-functions.bash

I checked `htop`, first ED was using around 38% CPU, after building with RelWithDebInfo, it only uses around 30% CPU

build RelWithDebInfo

---

ci/build-package.sh
installer/tue-install-impl.bash
setup/tue-functions.bash

- Also build release in CI
- Remove `--cmake-args` as it not needed and broke the usage of additional arguments
- Add build type to all build functions
Merge together with https://github.com/tue-robotics/tue-env-targets/pull/83

Fix release build

---

ci/build-docker-image.sh

`WARNING! Using --password via the CLI is insecure. Use --password-stdin.`
Apply fix as mention here: https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

Secure docker password

---

setup.bash

So targets can use all functions and variables defined above. Like the `qtcreator` target which requires TUE_SYSTEM_DIR, which is defined in tue-functions

move target import to end

---

ci/.travis.yml.multiple_pkgs.example
ci/azure-pipelines.yml.multiple_pkgs.example
ci/azure_commit_range.py
ci/packages.sh

Right now the CI only checks the modified packages against the last commit in a push. (in a PR, all commits are checked.) If you don't push every commit separately, these commit are put together in one build. But the still only the last commit was used to check for changed packages.
If this PR, this is fixed. For Travis, there is already a variable available. For azure, a script is needed to generate this. A external API is used to determine this. Azure is inconsistent and sometimes only provides one commit, while multiple commits were added since the last push. Therefore the script returns an empty string the case of just one commit. `Packages.sh` falls back to old implementation.
Update: Azure limits the number of commits to 200. In that case, the old method would be better.

Commit range to determine changed packages

---

setup/tue-functions.bash

`apt` mirrors face a race condition during updates. If the new mirror selected is was different than the existing one, there can be a `Hash sum mismatch` error.
One easy fix to this problem is to reset the existing lists by downloading them again.
An elegant fix is to only download lists that have this error, but would require excess tooling.

Cleanup existing apt lists before update

---

installer/tue-install-impl.bash

These lines shouldn't be here. Dependencies need to be specified in the targets, not in the package manager.
Merge along with tue-robotics/tue-env-targets#102

Fix hsr targets hack

---

setup/tue-functions.bash

This fixes the order of sourcing

(generate_setup_file) use installed targets

---

setup.bash

Needed for CI and automatically added to path on a normal PC after a reboot.
Fixes tue-robotics/tue-env-targets#137

Fix path issues of local installs in CI

---

installer/tue-install-impl.bash

Causes problem because tue-install-git is called in tue-install-hg to get hgcfg

fix tue-install-git overwriting tue-install-hg repo

---

ci/build-package.sh
ci/install-package.sh

When using `-it` in docker exec, the container expects an interactive terminal to be connected.
To have only color outputs `-t` should be used.
To have interactive inputs like `input | docker ...` or `docker ... <input` `-i` is to be used
Tested it on both Azure (https://dev.azure.com/tue-robotics/tue-robotics/_build/results?buildId=1918&view=results) and Travis (https://travis-ci.com/github/tue-robotics/hero_bringup)
Delete branch `fix/azure-ci` in tue_robocup and hero_bringup upon merge.

Fix Azure CI

---

installer/parse-install-yaml.py
installer/tue-install-impl.bash

It installs the target and its dependencies directly, so these can be used during the execution of the install.bash script. Though ROS packages including dependencies, both system and git, are not converted to a now target, as ROS packages shouldn't be executed during install scripts.
I don't see the need for a command line option. As a target should only be converted to a now target in case that is needed by an other target.

Add target-now feature

---

installer/tue-install-impl.bash

If a target exists an error is not thrown because we want to check if the target with a ros prefix exists. But this causes a problem for not ros targets depending on other targets. Therefore the return code of cmds should be checked

Correct error_handling of yaml install cmds

---

.github/workflows/main.yml

`continue-on-error` causes for the action to continue to run docker generation, while this shouldn't. This shouldn't have been there in the first place.
This fixes this incorrect behaviour: https://github.com/tue-robotics/tue-env/actions/runs/420599094

(actions) remove continue-on-error

---

installer/tue-install-impl.bash

if `ed_msgs` was pulled, `ed` would be skipped. Which is incorrect
```
array=()
array2=()
array+=/home/amigo/ed_msgs
array2+=:/home/amigo/ed_msgs:
[[ $array =~ /home/amigo/ed ]] && echo found
[[ $array2 =~ :/home/amigo/ed: ]] && echo found2
```
Will print `found`, but this shouldn't. It will not print `found 2`, which is correct.
Also I have tested that `[[ $array == *:/home/amigo/ed:* ]]` is faster than `[[ $array =~ :/home/amigo/ed: ]] `

Fix and speedup pull Q

---

ci/commit-range/action.yml

This should fix the issue in https://github.com/tue-robotics/ed_sensor_integration/runs/1674923505?check_suite_focus=true#step:4:9
I have tested this on my laptop with and older repo and a fresh clone. I can reproduce the error on the fresh clone. But the current implementation does work on my old repo, because it has commits from before rebasing.
The new solution does work on both repos and has the same output. I can't fully test the new solution as I don't have the full GitHub context, but I have tested all separate parts with a fake commit_list.
After we merge the new solution we can rerun the failing action, which should succeed then.

(CI)(commit-range) fix range for rebase pushes

---

installer/tue-install-impl.bash

Old pip dependency resolver does not consider dependency conflicts when selecting packages. The new resolver fixes this.
See image_recognition_keras:

pip: use new dep resolver

---

README.md
installer/tue-install-impl.bash

Many targets would run an update after adding an apt source. This makes sure that we only run one `apt-get update`.
It could be that the added source is incorrect, which would normally show up during the target and not later on. Though none of these targets checked the return code, so that check wasn't happening anyway.
So we should either accept it and run one update on the next call of `tue-install-system-now` or we should add checks to the return code in the targets.

tue-install-apt-get-update

---

Dockerfile
ci/install-package.sh

This way we can strip the forced apt update in the `install-package.sh` script

(Docker) remove temp tue files

---

.github/workflows/main.yml

There is no need to update as both the [generation](https://github.com/tue-robotics/tue-env/runs/1800614259?check_suite_focus=true) seems to work correctly and also the use with ssh in [`hero_bridge`](https://github.com/tue-robotics/hero_bridge/runs/1800625916?check_suite_focus=true).
From the [documentation](https://github.com/actions/virtual-environments/blob/ubuntu18/20210123.1/images/linux/Ubuntu1804-README.md) it is unclear what version of docker is used. But it seems to work...

(actions) don't update docker

---

installer/tue-install-impl.bash

When only installing git pip targets, the script to check the versions of the installed pkgs doesn't get any argument. So the script will return a non-zero error-code. This stops the installer, while nothing is wrong. So only check if the length is greater than zero.

(pip) don't check for version if only git pip targets

---

.github/workflows/main.yml

In case of a PR docker build, the PR was not the PR number but just `true` (https://github.com/tue-robotics/tue-env/pull/557/checks?check_run_id=2230989984#step:4:117). This PR fixes this.
The new behaviour matches the old behaviour on Travis (https://travis-ci.com/github/tue-robotics/tue-env/jobs/447483130#L311)

(actions) better parsing of branch and pr vars

---

installer/tue-install-impl.bash

Git is not guessing anymore it is a path object. It will only look for it as a branch.

fix try_branch_git
