setup/tue.bash_functions

Fixing robocup bash functions for new folder stucture

---

installer/targets/ros-festival/install.yaml

combined pull-request with text_to_speech repo

festival target

---

installer/targets/ros-robot_skills/install.yaml
installer/targets/ros-robot_smach_states/install.yaml
installer/targets/ros-tue_robocup/install.yaml

Merge the robot_smach_states and robot_skills repos to tue_robocup
@reinzor, can you check if this is ok? **First merge tue-robotics/tue_robocup#154**

Merge robot_* repos

---

setup.bash

Fix annoying perl language warnings

---

installer/targets/ros-gstreamer1.0/install.yaml

This reverts commit 081b33ead11c95aea62c5cff628ff31a5be85c93.

Revert "fix(targets): remove gstreamer1.0 install.yaml file"

---

installer/targets/robot-user/setup

Automatically sets ROS_IP's when we are on the robot network and if we
are not on the robot. By doing this, we don't have to synchronize all
laptop and robot pc host files.

feature(ROS_IP): Set ROS IP when we are on robot network

---

installer/targets/amigo-start/install.yaml

Always run MoveIt since we always want to do cartesian planning

refactor(): Manipulation to astart

---

installer/targets/amigo-user/setup

No specific challenge functions and/or different set envs

refactor(): remove all astart and amiddle functions

---

installer/targets/megatools/setup

mega-service-restart alias restarts the systemd service

feature(megatools): Alias to restart mega service

---

installer/targets/gitsu/gitsu.txt

Add Tim Assman, remove Jos Elfring, some spacing fixes.
Not tested at all

Update gitsu list

---

installer/targets/ros-amcl/install.yaml
installer/targets/ros-base_local_planner/install.yaml
installer/targets/ros-carrot_planner/install.yaml
installer/targets/ros-clear_costmap_recovery/install.yaml
installer/targets/ros-costmap_2d/install.yaml
installer/targets/ros-dwa_local_planner/install.yaml
installer/targets/ros-fake_localization/install.yaml
installer/targets/ros-map_server/install.yaml
installer/targets/ros-move_base/install.yaml
installer/targets/ros-move_base_msgs/install.yaml
installer/targets/ros-move_slow_and_clear/install.yaml
installer/targets/ros-nav_core/install.yaml
installer/targets/ros-navfn/install.yaml
installer/targets/ros-navigation/install.yaml
installer/targets/ros-robot_pose_ekf/install.yaml
installer/targets/ros-rotate_recovery/install.yaml
installer/targets/ros-voxel_grid/install.yaml

Please not that reviewing this commit effectively means you are reviewing this as well:
https://github.com/tue-robotics/navigation/compare/hydro-devel...kinetic-devel
(Untested)

Switch to kinetic-devel branch to fix eigen3 errors

---

installer/targets/ros-challenge_storing_groceries/install.yaml

@Jip238 note that I renamed the challenge to match the rulebook: challenge_storing groceries

Add challenge_storing_groceries

---

installer/targets/ros-sergio_torso_calibration/install.yaml

SERGIO torso targets

---

installer/targets/ros-robot_smach_states/install.bash

Already in https://github.com/tue-robotics/tue-env/blob/master/installer/scripts/tue-install-impl#L661

Removing robot_smach_states install.bash target

---

installer/targets/era-test/install.bash
installer/targets/era/install.bash

Moved to graveyard a while ago

Delete era targets

---

installer/targets/amigo2/install.bash
installer/targets/bower/install.bash
installer/targets/gitsu/install.bash
installer/targets/grunt/install.bash
installer/targets/nodejs/install.bash
installer/targets/roboticssrv/install.bash
installer/targets/ros-kinect_driver/install.bash
installer/targets/ros/install.bash
installer/targets/sergio1/install.bash
installer/targets/sergio2/install.bash

For consistency, always assume answer is yes

---

ci/.travis.yml.example
ci/build-package.sh
ci/install-package.sh

Works, see https://github.com/tue-robotics/amigo_bringup/pull/47

Add support for pull requests instead of only compiling branches

---

ci/build-docker-image.sh
ci/build-package.sh
ci/install-package.sh
installer/scripts/bootstrap
installer/scripts/bootstrap-ros-indigo
installer/scripts/bootstrap-ros-jade
installer/scripts/bootstrap-ros-kinetic
installer/scripts/tue-install
installer/scripts/tue-install-impl

This gives the user a change to fix it before a lot of potential useless commands are executed

Stop on errors in install and bootstrap scripts. No use in going on

---

installer/targets/ros-r5cop_demo/install.yaml

We probably did not fork it for nothin'

Aquire r5cop demo from our own repository. 

---

ci/install-package.sh

Should solve https://github.com/tue-robotics/tue_robocup/issues/328

Pipe to grep always succeeds, solved differently by modifying message

---

ci/build-docker-image.sh
ci/build-package.sh
ci/install-package.sh
installer/scripts/bootstrap
installer/scripts/bootstrap-ros-indigo
installer/scripts/bootstrap-ros-jade
installer/scripts/bootstrap-ros-kinetic
installer/scripts/tue-install
installer/scripts/tue-install-impl

It breaks `tue-get update` on my machine

Revert "Stop on errors in install and bootstrap scripts"

---

installer/targets/ros-smach/install.yaml
installer/targets/ros-smach_msgs/install.yaml
installer/targets/ros-smach_ros/install.yaml

The commits are finally merged so we can unfork:
ros/executive_smach@5df1483d6dfb58d7a018368a330a70534acf6e2b, ros/executive_smach@5225d6071b6a0151df0b09cf550aa3ca581df7c4

Unfork smach

---

installer/scripts/tue-install-impl

pip freeze converted to lowercase to remove case sensitivity

---

installer/targets/ros-tue_maps/install.yaml

Remove tue-maps

---

installer/targets/amigo-user/setup

convert connect-to-amigo-subnet to a function

---

installer/scripts/tue-install-impl

Try with apt-get remove package and then installing a target that depends on it.

Fix apt package checking

---

installer/targets/gitsu/gitsu.txt

Fix email address

---

installer/targets/matthijs/install.yaml
installer/targets/ros-swri_console/install.yaml
installer/targets/ros-swri_console/setup
installer/targets/ros-usb_cam/install.yaml

Small changes to targets

---

installer/scripts/tue-install-impl
setup/tue.bash_functions

Small bugfixes to improve robustness and speed

---

installer/targets/ros-libfreenect-dev/install.yaml

together with https://github.com/tue-robotics/kinect_driver/pull/5

Add ros-libfreenect-dev target

---

installer/targets/ros-python-xhtml2pdf/install.yaml

```
from html5lib import treebuilders, inputstream
ImportError: cannot import name inputstream
```
https://github.com/xhtml2pdf/xhtml2pdf/issues/318

broken dependency

---

installer/targets/docker/install.bash

fix docker

---

installer/targets/ros-image_recognition_tools/install.yaml

Merge after https://github.com/tue-robotics/image_recognition/pull/33

Add installer for image_recognition_tools

---

installer/targets/ros-python-sklearn/install.yaml

Missing target for dependency of image_recognition_tools

Add ros-python-sklearn

---

installer/scripts/parse-install-yaml
installer/scripts/tue-install-impl
installer/targets/pycharm/install.yaml

Add snap functionality, move pycharm to snap

---

installer/targets/ros-shape_msgs/install.yaml

add shape_msgs target

---

installer/targets/ros-python-tensorflow-pip/install.yaml

Needed for https://github.com/tue-robotics/image_recognition/pull/50

Require tensorflow 1.4.1

---

ci/.travis.yml.multiple_pkgs.example
ci/build-package.sh
ci/packages.sh

See https://travis-ci.org/tue-robotics/wire/builds/331339427 and https://travis-ci.org/tue-robotics/wire/builds/331339402

Correct detection changed pkgs in multi pks repo's

---

installer/targets/cmdgen/install.bash

This is the reason tue_robocup PR is failing

Adding assume-yes to cmdgen install

---

ci/.travis.yml.multiple_pkgs.example
ci/packages.sh

Needed in https://github.com/tue-robotics/action_server, because it contains the folder 'doc'

allow excluding folders

---

ci/packages.sh

fixes ```packages.sh: line 13: [: robot_smach_states: binary operator expected```

fix packages.sh

---

installer/targets/ros-diagnostic_updater/install.yaml

Forked at https://github.com/tue-robotics/diagnostics
Used in https://github.com/tue-robotics/image_recognition/pull/55.

Use our fork of the ROS diagnostic_updater

---

installer/targets/ros-python-tensorflow-pip/install.bash

1.7.* doesn't work. I know that this version does work.

Revert tensorflow to 1.4.1

---

installer/scripts/tue-install-impl

This keeps the style of the git output. While not printing, if msg is empty.

Check against echo, print original res

---

installer/targets/amigo-chrony-client-pc/install.bash
installer/targets/amigo-user/setup
installer/targets/amigo1/install.bash
installer/targets/git-hooks/install.bash
installer/targets/gitsu/install.bash
installer/targets/jetson/README.md
installer/targets/ros-python-sip/install.bash
installer/targets/sergio-chrony-client-pc/install.bash
installer/targets/sergio-user/setup
installer/targets/sergio1/install.bash
installer/targets/sublime3/install.bash
installer/targets/tue-all/install.bash
installer/targets/tue-common/install.bash
installer/targets/tue-common/setup
installer/targets/tue-fancydesktop/configs/variety/variety.conf
installer/targets/tue-hardware/setup
installer/targets/vim/install.bash
setup.bash
setup/tue.bash_functions

To reduce dependency of having the installer in ~/.tue

replace .tue by $TUE_DIR, when possible

---

installer/targets/ros-python-pillow/install.yaml
installer/targets/ros-python-tornado/install.yaml
installer/targets/tue-robocup-at-home/install.yaml

That is a dependency of tue-dev so you should get the vizbox if all is correct

Include ros-vizbox in robocup-at-home

---

installer/scripts/tue-install-impl
setup/tue.bash_functions

for all the scripts on the server side:
`~/MEGA/tools/server`
please review as soon as possible.

new git workflow

---

installer/targets/ros-python_orocos_kdl/install.bash

all pc's should have been updated by now

don't force update libcppunit-dev anymore

---

installer/targets/ccache/install.yaml
installer/targets/ccache/setup
installer/targets/robot-user-robot-common/install.yaml
installer/targets/robot-user/install.yaml
installer/targets/robot-user/setup
installer/targets/robot/install.yaml
installer/targets/robot/setup
installer/targets/tue-dev/install.yaml
setup.bash

small refactor in robot and robot-user target

Install ccache also on robots

---

installer/targets/gitsu/gitsu.txt

Add Dorus to gistu list

---

installer/targets/ros-keras_ros/install.bash

Old link is broken, you can test yourself.

Fix keras age_estimation model link

---

installer/scripts/parse-ros-package-deps

add all format2 dep tags to package parsing

---

installer/scripts/tue-install-impl

Fixes:
- Version checking was wrong
- user version was updated/installed, while system version is used
- remove unused if check, if statement was the same as if statement of higher level
Before fix: https://travis-ci.org/tue-robotics/telegram_ros/builds/461249039#L2710
After fix: https://travis-ci.org/tue-robotics/telegram_ros/jobs/461252304#L2803

Fix pip upgrade

---

installer/targets/ros-python-catkin-lint/install.yaml

For image_recognition packages

Add python-catkin-lint

---

installer/targets/ros/install.bash

update rosdep, otherwise it can cause issues with catkin_lint

update rosdep once every powercycle

---

installer/targets/ros-python-tensorflow-hub-pip/install.yaml
installer/targets/ros-python-tensorflow-pip/install.bash

merge together with tue-robotics/image_recognition#75
Tensorflow version requirement according: https://www.tensorflow.org/hub/installation

Add tensorflow-hub and set new version req of tensorflow

---

installer/targets/ros-sdfformat/install.bash

No need to use install-system-now in sdfformat

---

setup/tue-functions.bash

show contents of target

---

installer/targets/speech-recognition-dev/install.yaml

I would like to have this as a dev target which we can get rid of later when all the dependencies are well understood and integrated into the speech_recognition repo.

Added speech-recognition-dev target

---

installer/scripts/tue-install-impl.bash

Also use the whoami command since the $USER variable is not guaranteed to exist

Support spaces in filenames and create target directory if it does not yet exist

---

installer/targets/gazebo_models/setup

gazebo models as backup, so put it at the front

correct order of gazebo models

---

README.md
installer/scripts/tue-install-impl.bash
installer/targets/tue-fancydesktop/install.bash

Can be tested by creating a new target

Support patterns in tue-install-cp

---

installer/tue-install.bash

Fix version of targets repo in CI

---

Dockerfile
installer/tue-install.bash

I think this one is a little bit cleaner than solution of @ar13pit.
It works, see https://travis-ci.org/tue-robotics/hero_bringup/builds/490291841
Also fixed the issue with hsr apt sources, which are https
Fixes #356

Fix targets in CI

---

installer/tue-install-impl.bash

Also a bugfix because `software-properties-common` might not be available on every ubuntu install

Install not often-used tooling on demand

---

README.md
installer/parse-install-yaml.py

Might be useful when switching to melodic in the future but when not all packages are available yet:
http://repositories.ros.org/status_page/compare_kinetic_melodic.html

Add option to specify different sources per ROS distro

---

setup/tue-functions.bash

When I merged the enhancement #361 to #360 
These redundancies were added by git. I don't know why this happened.

Remove duplicate ssh functions

---

installer/tue-install-impl.bash

Current log is not very useful and could be much more extensive.
Made it identical to stdout so you don't have to understand multiple ways of logging things as user.

Let log be identical to output

---

.dockerignore
.travis.yml
Dockerfile
ci/build-docker-image.sh
ci/build-package.sh
ci/install-package.sh
installer/tue-install.bash

- Reduce the layers in the docker image
- CI scripts cleanup
- Execute CI scripts only in CI environment

Docker and CI cleanup

---

Dockerfile

Remove CI variables from Docker image environment as inherited images still retain the variables.

test container based CI settings

---

ci/install-package.sh

Merge after CI for tue-robocup shows target branch pull

Fix CI install package

---

installer/tue-get-dep.bash
installer/tue-install-impl.bash
installer/tue-install.bash
setup/tue-data.bash
setup/tue-env.bash
setup/tue-functions.bash
setup/tue-misc.bash

- Add possibility for relative and absolute source files
- Check if changing the lines, changes the target file. This reduces the need for sudo.
- Add debugging statements
Also fix all shellcheck errors
Maybe best to check each commit separate

Extend 'add text'

---

setup/tue-functions.bash

Added colors, spacing and made sure the name of a removed branch is displayed only after a branch has been removed.

Update git-clean-local echo statements

---

ci/.travis.yml.multiple_pkgs.example
ci/azure-pipelines.yml.example
ci/azure-pipelines.yml.multiple_pkgs.example
ci/packages.sh

- Update CI scripts to be compatible with Azure Pipelines
- Add example configs for Azure Pipelines

Compatibility with Azure Pipelines

---

ci/azure-pipelines.yml.example
ci/azure-pipelines.yml.multiple_pkgs.example
ci/packages.sh

- If ci config changes, build all pkgs
- If other files in main folder changes, no pkg is build

Fix ci issues

---

ci/azure-pipelines.yml.multiple_pkgs.example

This fixes #429
See https://dev.azure.com/tue-robotics/tue-robotics/_build/results?buildId=734&view=results
I would squash this PR.

(azure) only run if PACKAGES_DICT != {}

---

ci/install-package.sh
dockerfiles/tue-env-cuda-10.0.Dockerfile
dockerfiles/tue-env.Dockerfile

Azure keeps providing too much problems, so reverting it for now. Coming up with long-term solution afterwards.

Revert apt mirror in CI

---

Dockerfile
installer/tue-install-impl.bash

Fixes from melodic devel

---

installer/parse-install-yaml.py

`return 0` is not really needed. but I prefer it.

typo and small fix

---

ci/azure-pipelines.yml.example
ci/azure-pipelines.yml.multiple_pkgs.example

Merge with tue-robotics/tue_robocup#1003

Update azure examples

---

Dockerfile
README.md
ci/install-package.sh
installer/bootstrap.bash
installer/parse-ros-package-deps.py
installer/tue-get-dep.bash
installer/tue-install-impl.bash
setup/tue-env-config.bash
setup/tue-functions.bash

Performed a two-way-sync with nobleo-get :). Contains some new options mostly

Nobleo backport

---

.editorconfig
README.md
installer/github-releases.py
installer/tue-install-impl.bash
setup/github-releases.py

Closes #379 
After merge make appropriate changes to `ros-speech_recognition` and `ros-dashboard` targets from tue-robotics/tue-env-targets#30

Github get/create releases

---

installer/tue-install-impl.bash

Weird branch name to test in action_server ci

Add more errors in case installing fails

---

Dockerfile
setup/tue-env-config.bash
setup/tue-functions.bash

Some cleanup on changes in SSH

---

installer/tue-install-impl.bash

Review and merge after #477 is merged.

New location of repos

---

README.md
ci/README.md

Merge with tue-robotics/tue-env-targets#151

Add ssh docs

---

installer/check-pip-pkg-installed-version.py
installer/tue-install-impl.bash

Speed up of installed pip pkgs

---

installer/tue-install-impl.bash

Merge after https://github.com/tue-robotics/hgcfg/pull/2

Use mercurial on python3

---

installer/parse-install-yaml.py
installer/tue-install-impl.bash

Use C loader of yaml; lsb_release instead of distro

---

.travis.yml
Dockerfile
ci/build-docker-image.sh
ci/install-package.sh

- Replace `master` tag with `latest` for default branch as that is the docker nomenclature
- Use travis job name variable in .travis.yml
- Use colorized terminal in Docker

Standardize docker image name

---

installer/tue-install-impl.bash
installer/tue-install.bash

Sync updates the url of the submodules

Submodule sync

---

ci/build-package.sh
setup/tue-functions.bash

Merge together with https://github.com/tue-robotics/tue-env-targets/pull/166

(tue-make) remove -DCATKIN_ENABLE_TESTING=OFF

---

ci/install-package.sh

ci: Fix docker carriage return

---

installer/tue-install-impl.bash
setup/tue-functions.bash

Add regex support

---

.travis.yml
ci/azure_commit_range.py
ci/ssh-merge-known_hosts.py
installer/github-releases.py
installer/parse-package-xml.py

Add Python Black check

---

README.md
installer/tue-install-impl.bash

Review and merge after #529
Merge together with https://github.com/tue-robotics/tue-env-targets/pull/184

feat(ci_ignore): Ignore an entire target in CI or bash or yaml

---

README.md

doc(README): target-now

---

ci/build-package.sh
setup/tue-functions.bash

This reverts commit 1ce74737c38ce1b45f23c9f5fb43740a7846835c.
Merge together with https://github.com/tue-robotics/navigation/pull/22

Revert "(tue-make) remove -DCATKIN_ENABLE_TESTING=OFF"

---

installer/tue-install-impl.bash

Fixes https://github.com/tue-robotics/tue-robotics.github.io/runs/1466822946?check_suite_focus=true#step:3:63

Fix broken pipe in GitHub Actions

---

README.md

and show `default` can also have a source

Show environment usage

---

Dockerfile
README.md
ci/build-docker-image.sh
installer/bootstrap.bash
installer/tue-get-dep.bash
installer/tue-install-impl.bash
installer/tue-install.bash
setup/tue-data.bash
setup/tue-functions.bash

Compatible with older versions, temporarily

noetic-devel

---

installer/tue-install.bash

As this is the last echo of targets. All new echos should start on a new line.

echo with new line in targets handling

---

ci/install-package.sh
installer/tue-install-impl.bash
installer/tue-install.bash
setup/tue-functions.bash

This branch is only called `ack`, so that there is a target folder with the same name.

Make clear that branch is checked out

---

Dockerfile
ci/install-package.sh
ci/main/action.yml

- Changes behavior of install script by setting the branch option to be empty string for default branch
- Do not specify branch option in Docker image creation
Closes #547

fix: Fix CI behavior

---

ci/azure-pipelines.example.yml
ci/azure-pipelines.multiple_pkgs.example.yml
ci/build-docker-image.sh
ci/build-package.sh
ci/install-package.sh
ci/packages.sh
ci/set-branch.sh
ci/test-package.sh
ci/travis.example.yml
ci/travis.multiple_pkgs.example.yml
ci/update-docker.bash
installer/tue-install-impl.bash

Get rid of unnecessary spacing in logging.

Fix CI for azure/travis

---

installer/tue-get-dep.bash
installer/tue-install-impl.bash
installer/tue-install.bash

These changes from #562 can definitely be merged. The other changes are all related to the version/branch in `tue-install-git`, these do change the behaviour significantly. I don't think those should be merged.

Cosmetic stuff2

---

installer/tue-get-dep.bash
installer/tue-install-impl.bash
installer/tue-install.bash
setup/tue-functions.bash

Text blink makes text hard to read and slows down the developer workflow.

style: remove blinking style from messages
